version: '3.8'

networks:
  localnet:
    driver: bridge

services:
 
  postgres:
    container_name: dbServer
    image: lquarterolo/proj_docker:latest
    networks:
      - localnet
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}

  adminer:
    image: adminer
    networks:
      - localnet
    restart: always
    ports:
      - 8080:8080